CREATE TABLE TOPIC
(
    ID BIGINT AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    GMT_CREATE BIGINT NOT NULL,
    GMT_MODIFIED BIGINT NOT NULL,
    AUTHOR BIGINT NOT NULL,
    COMMENT_COUNT INT DEFAULT 0,
    VIEW_COUNT INT DEFAULT 0,
    LIKE_COUNT INT DEFAULT 0,
    TAG VARCHAR(256),
    CONSTRAINT QUESTION_PK
        PRIMARY KEY (ID)
);