CREATE TABLE LIKE
(
    ID BIGINT AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    LIKED BIGINT NOT NULL,
    TYPE INT NOT NULL,
    GMT_CREATE BIGINT NOT NULL,
    CONSTRAINT LIKE_PK
        PRIMARY KEY (ID)
);